// Import prisma from the root client file
import { prisma } from "../../prisma.client.js";
export {
  saveOrder,
  getOrders,
  getAdSpendTotal,
  getSourceMetrics,
  upsertSourceAdSpend,
  addSourceAdSpend,
  upsertToolAttribution,
  getSpendEntries,
  updateSpendEntry,
  deleteSpendEntry,
  upsertCreativeMetricDaily,
  upsertCreativeMetricBatch,
  getConnectorCredential,
  listConnectorCredentials,
  upsertConnectorCredential,
  listAllConnectorCredentials,
  getCampaignPerformance,
  createConnectorSyncRun,
  getRecentConnectorSyncRuns,
  getLastSuccessfulConnectorSyncRun,
  getSyncFreshnessByShop,
  getDataQualitySummary,
  listAlertRules,
  listAlertRuleSettings,
  upsertAlertRuleSetting,
  markAlertRead,
  listAlertEvents,
  evaluateAndStoreAlerts,
  getDashboardPreference,
  upsertDashboardPreference,
  listAiPromptTemplates,
  createAiPromptTemplate,
  deleteAiPromptTemplate,
  setAiPromptTemplatePinned,
  createAiPromptRun,
  listAiPromptRuns,
  listMarketBenchmarks,
  listCampaignActionItems,
  getCampaignUserInsights,
  createCampaignActionItem,
  updateCampaignActionStatus,
  listActivationDestinations,
  createActivationDestination,
  updateActivationDestination,
  deleteActivationDestination,
  triggerActivationDestination,
  listAudienceSyncRules,
  createAudienceSyncRule,
  updateAudienceSyncRuleStatus,
  deleteAudienceSyncRule,
  listAudienceSyncRuns,
  runAudienceSyncRules,
  getCreativePerformanceScores,
  getCreativeFatigueRisks,
  getBudgetReallocationSuggestions,
  createBudgetReallocationDecision,
  listBudgetReallocationDecisions,
  ingestUniversalSignalEvents,
  getUniversalShopOverview,
  getUniversalInsights,
  listUniversalSources,
} from "./db.js";

// Re-export for convenience
export { prisma };
